Infrastructure: fix PTB updates for mac/linux (#7263)
<!-- Keep the title short & concise so anyone non-technical can
understand it,
     the title appears in PTB changelogs -->
#### Brief overview of PR changes/additions
PTB updates for mac/linux don't seem to be registered anymore due to an
[odd
error](https://github.com/Mudlet/Mudlet/actions/runs/9411024816/job/25923640567):

```
Error: Unable to process file command 'env' successfully.
Error: Invalid format 'https://make.mudlet.org/snapshots/1b7b76/Mudlet-4.17.2-testing-834d7d01-linux-x64.AppImage.tar'
```

Changed syntax used to set the variable, maybe this will work better?
#### Motivation for adding to Mudlet
Mac/Linux PTBs weren't seeing new updates
#### Other info (issues closed, discussion etc)