BugFix: correct a failure to convert a QString to a char array
Cause a build failure but only in some (Clang) compilers:
"Error: /Users/runner/work/Mudlet/Mudlet/src/TLuaInterpreter.cpp:5382:97:
 error: cannot pass object of non-trivial type 'QString' through variadic
 function; call will abort at runtime [-Wnon-pod-varargs] in:
lua_pushfstring(L, "the special exit name/command \"%s\" does not exist in
 room id %d", dir, fromRoomID);

Signed-off-by: Stephen Lyons <slysven@virginmedia.com>