Change ports path from . to ./lua
Just using . didn't work:

  error: while loading /home/runner/work/Mudlet/Mudlet/3rdparty/our-vcpkg-dependencies/./vcpkg.json:
  $ (a manifest): missing required field 'name' (an identifier)
  $ (a manifest): expected a versioning field (one of version, version-date, version-semver, or version-string)Failed to load port hunspell from /home/runner/work/Mudlet/Mudlet/3rdparty/our-vcpkg-dependencies/.