Drop all locks (#4176)
* Drop all locks.

Exception: The map import lock is actually necessary, but we're not
doing any multithreading *or* scoped unlocking here. Thus a simple
boolean flag works just as well.

* restore Discord::getDiscordUserDetails code

* ... and remove the locking.