Infrastructure: Revert update to Boost 1.77.0 (#6029)
Reverts Mudlet/Mudlet#5916

While it finds Boost correctly, using Boost later down the road fails:

```
TAstar.h:30:10: fatal error: boost/graph/adjacency_list.hpp: No such file or directory
 #include <boost/graph/adjacency_list.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Should have waited for CI to pass before merging, that was a bit premature!