Infrastructure: Update Powershell scripts (#7043)
#### Brief overview of PR changes/additions
- Install 7z before ccache, as this is needed to extract that
- Improve error reporting parameters

#### Motivation for adding to Mudlet
-
[setup-windows-sdk.ps1](https://github.com/Mudlet/Mudlet/blob/development/setup-windows-sdk.ps1)
fails otherwise with "file not found" error mentioning 7z:
```
.\setup-windows-sdk.ps1
workingBaseDir is C:\src\
Using C:\Qt\5.14.2\mingw73_32 as QT base directory.
==== compiling and installing ccache ====
---- installing ccache ----
---- Downloading ----
---- Extracting source distribution ----
Start-Process: C:\dev\GitHub\Mudlet\CI\appveyor.functions.ps1:79
Line |
  79 |  … exitCode = (Start-Process -FilePath $cmd -ArgumentList $parameter -Wa …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | This command cannot be run due to the error: Das System kann die angegebene Datei nicht finden.
Exception: C:\dev\GitHub\Mudlet\CI\appveyor.functions.ps1:84
Line |
  84 |      throw $errorMessage
     |      ~~~~~~~~~~~~~~~~~~~
     | Error executing command: 7z
```

#### Other info (issues closed, discussion etc)
- Probably broken since #6193
- Bug however only appears if system does not have 7z installed prior

---------

Co-authored-by: Vadim Peretokin <vperetokin@hey.com>